# CREDITS TO: https://www.youtube.com/watch?v=HX9RsIQktuQ
version: "3.8"
services:
  message-service:
    build: ./message-service
    env_file:
      - ./message-service/.env
    ports:
      - "3000:3000"
    networks:
      - my_custom_network

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - my_custom_network

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - my_custom_network

  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    networks:
      - my_custom_network
    ports:
      - "8080:8080"
    depends_on:
      - kafka
  
networks:
  my_custom_network:
    external: true